exos: exo1 exo2

exo2: exo2_main.o exo2_fonction.o
	gcc exo2_main.o exo2_fonction.o -o exo2

exo2_main.o: exo2_main.c 
	gcc -c exo2_main.c

exo2_fonction.o: exo2_fonction.c
	gcc -c exo2_fonction.c

exo1: exo1_main.o exo1_fonction.o
	gcc exo1_main.o exo1_fonction.o -o exo1

exo1_main.o: exo1_main.c 
	gcc -c exo1_main.c

exo1_fonction.o: exo1_fonction.c
	gcc -c exo1_fonction.c


